/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TChat: typeof import('@tdesign-vue-next/chat')['Chat']
    TChatAction: typeof import('@tdesign-vue-next/chat')['ChatAction']
    TChatContent: typeof import('@tdesign-vue-next/chat')['ChatContent']
    TChatLoading: typeof import('@tdesign-vue-next/chat')['ChatLoading']
    TChatSender: typeof import('@tdesign-vue-next/chat')['ChatSender']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TPopup: typeof import('tdesign-vue-next')['Popup']
  }
}
